### ISSUE TITLE
Account Info getter is stuck sometimes

### ISSUE THREAD

**Issue by clangenb** [integritee-network/try-incognitee-app#85] opened 2024-11-06 13:43 UTC
The balance doesn't update after shielding. It seems that the account info getter is stuck somewhere, as I see this message often:

```
[fetchIncogniteeBalance] already updating. waiting...
```
A refresh of the page resolves the problem.

**Comment by clangenb** [comment] 2024-11-06 13:45
It seems that opening the `ChooseWalletOverlay` causes this.

**Comment by brenzi** [comment] 2024-11-07 07:20
`[fetchIncogniteeBalance] already updating. waiting...` may be misleading. it just means we'll pause the balance polling. usually, the reason is what it says, but opening the chooseAccountOverlay does the same.

I was able to reproduce one thing:
1. choose account 
2. open chooser again and pick the same account
3. overlay won't close
4. if I manually close the overlay, the balance won't poll anymore

**Comment by brenzi** [comment] 2024-11-07 07:58
should be fixed with ebce9760f8e6f75198ce39576e0a50db9c327e31

**Closed by brenzi** 2024-11-07 07:58 UTC
